name: pcic_mobile_app
description: "Q"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.1
  flutter_lints: ^3.0.2
  intl: ^0.19.0
  provider: ^6.1.2
  csv: ^6.0.0
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  google_sign_in: ^6.2.1
  file_picker: ^8.0.0+1
  firebase_database: ^10.4.11
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  latlong2: ^0.9.1
  flutter_map_location_marker: ^8.0.8
  gpx: ^2.2.2
  path_provider: ^2.1.2
  screenshot: ^2.3.0
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  flutter_downloader: ^1.11.6
  url_launcher: ^6.2.5
  open_file: ^3.3.2
  camera: ^0.10.5+9
  flutter_animate: ^4.5.0 #decide latur
  # flutter_plugin_android_lifecycle: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/config/.env
    - assets/storage/images/
    - assets/storage/tasks/
    - assets/image/
    - assets/animations/
    # - assets/cache.db
    # - assets/icon/
