name: pcic_mobile_app
description: "Q"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # for flutter
  intl: ^0.19.0

  # utils
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  # camera: ^0.11.0
  # device_info_plus: ^10.1.0 # permission handler (not used)
  # flutter_dotenv: ^5.1.0 # (not used)

  # file
  csv: ^6.0.0
  gpx: ^2.2.2

  # map
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.8
  image_picker: ^1.0.7
  latlong2: ^0.9.1

  # design
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.0

  flutter_lints: ^4.0.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  file_picker: ^8.0.0+1
  flutter_map_cancellable_tile_provider: ^2.0.0
  path_provider: ^2.1.2
  fluttertoast: ^8.2.4
  flutter_downloader: ^1.11.6
  url_launcher: ^6.2.6
  open_file: ^3.3.2
  signature: ^5.4.1
  external_path: ^1.0.3
  url_strategy: ^0.2.0
  flutter_launcher_icons: ^0.13.1
  xml: ^6.5.0
  flutter_svg: ^2.0.10+1
  uuid: ^4.4.0
  archive: ^3.5.0
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  tuple: ^2.0.2
  geocoding: ^3.0.0
  flash: ^3.1.0
  cloud_firestore: ^4.17.3
  lottie: ^3.1.2

  # firebase
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  firebase_database: ^10.4.11
  firebase_storage: ^11.7.5

  # surely not used
  # screenshot: ^2.3.0
  # flutter_plugin_android_lifecycle: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/pcic_logo.png"
  web:
    generate: true
    image_path: "assets/image/pcic_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/pcic_logo.png
    - assets/storage/images/
    - assets/storage/tasks/
    - assets/image/
    - assets/animations/
    - assets/storage/mergedtask/
    # - assets/cache.db
    # - assets/icon/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
